[package]
name = "threadly-platform"
version = "0.1.0"
description = "A modern community platform with integrated news, virtual currency, and YouTube channel integration"

[dependencies]
"wasmer/static-web-server" = "=1.1.0"

[fs]
"/app" = "./out"

[[command]]
name = "start"
module = "wasmer/static-web-server:webserver"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--root=/app", "--port=8080"]
env = [
  "NEXTAUTH_SECRET=threadly-secret-key",
  "NEXTAUTH_URL=http://localhost:3000"
]